<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.2" />
  </ItemGroup>

  <!-- Тестовый проект лежит в подпапке — исключаем его файлы из основного проекта -->
  <ItemGroup>
    <Compile Remove="ProjectWork.Tests\**" />
    <Content Remove="ProjectWork.Tests\**" />
    <None Remove="ProjectWork.Tests\**" />
    <EmbeddedResource Remove="ProjectWork.Tests\**" />
  </ItemGroup>

</Project>
